# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40bfe2ac550b54c4f60e7575846a9f92308390dd3615dbdcb3f402ed10ff1b4eb3e4411862df2de1bdc6030fa21550d2a7b028b1bb7673a5871e6e0839a07334
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyCf3_dVdwgtzKXxpj26bp4FqAMP4_L8ozw") %>



test:
  secret_key_base: 058e8d25dc3a97a7b71f2641b6b297161dd9da1f530144980baee9a7456dafc9a7e0ae3a25a3d358b18e9f1d14799c817619bdae56fc6819594521b887d82892
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyCf3_dVdwgtzKXxpj26bp4FqAMP4_L8ozw") %>

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  google_api_key:  <%= ENV.fetch("SECRET_KEY_BASE", "AIzaSyCf3_dVdwgtzKXxpj26bp4FqAMP4_L8ozw") %>
